name: Backend Bug Report
description: Create a backend bug report.
title: "[BACKEND-BUG]: "
type: "Bug"
labels: ["backend", "bug"]
projects: ["FuchsiaRush/1"]
body:
  - type: textarea
    id: bug
    attributes:
      label: Your bug report
      description: Please describe how to reproduce your bug step by step!  
      placeholder: What happened and how / what did you expect to happen?
