name: Main Branch Deployment

on:
  
  push:
    tags:
      - "v*"
  workflow_dispatch:
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 #action um alles abzurufen

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3 #login in die Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]') # Get the branch name in lowercase
          docker build . -t ghcr.io/$REPO_LOWER/$REPO_LOWER:latest
          docker build . -t ghcr.io/$REPO_LOWER/$REPO_LOWER:$BRANCH_NAME
 
      - name: Push Docker image to GitHub Packages
        run: |
          REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]') # Get the branch name in lowercase
          docker push ghcr.io/$REPO_LOWER/$REPO_LOWER:latest
          docker push ghcr.io/$REPO_LOWER/$REPO_LOWER:$BRANCH_NAME

      #selfmade
 
