name: Main Branch Deployment

on:
  
  push:
    tags:
      - "v*"
  workflow_dispatch:
      
env:
  IMAGE_NAME: ghcr.io/${{ toLower(github.repository) }} #setze die Varibale auf den Packages link mit /name des repos

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 #action um alles abzurufen

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3 #login in die Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Container
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
